version: "3.9"

x-logging: &default-logging
  options:
    max-size: "10m"
    max-file: "3"
  driver: json-file

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      target: production
    logging: *default-logging
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      target: production
    logging: *default-logging
    env_file:
      - ./frontend/.env
    ports:
      - "3000:80"

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    logging: *default-logging
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo_data:/data/db

volumes:
  mongo_data:
